### ISSUE TITLE
Nested Menu Item Not Rendered

### ISSUE THREAD

**Issue by thekenshow** [backdrop-contrib/bootstrap_lite#10]
I created a theme based on bootstrap_lite and cannot get nested menu item to render in my theme or the latest bootstrap_lite version. 

I’ve attached screen shots that show the primary menu configuration, the rendered menu, and the HTML. The Accommodations page in this example is published. The parent menu item, About Us, has **Display as expanded** selected. The Accommodations menu item should appear in the nav bar under About Us, but does not.

![screen shot 2016-08-08 at 11 06 35 am](https://cloud.githubusercontent.com/assets/998832/17484513/47ac690a-5d58-11e6-8968-88ba2c84fdd2.png)

![screen shot 2016-08-08 at 11 02 22 am](https://cloud.githubusercontent.com/assets/998832/17484479/0a18fe96-5d58-11e6-8ac2-6294f7ac3cf2.png)

![screen shot 2016-08-08 at 11 02 59 am](https://cloud.githubusercontent.com/assets/998832/17484484/13d32b32-5d58-11e6-904b-cba81e83ad3c.png)

**Comment by Gormartsen** [comment]
hi @thekenshow 
Tnx for issue.

I remember that I had something like this before.

If I remember it properly, there is a limit of nested items.

Try to redefine theme menu for primary and make sure that it goes dipper than 1 level.

I remember something connected with it in primary secondary menus.

Maybe this one can help.
https://api.backdropcms.org/api/backdrop/core%21includes%21menu.inc/function/menu_local_tasks/1

Let me know if you could not find it.

If I remember it properly, you need to completely redefine how menu tree get menu items include nested levels.

**Comment by thekenshow** [comment]
Thanks for the info. Looks like the standard Header Block provided in the default layout doesn’t have the depth configuration for a menu that a custom block does (see attached screen shots). That seems like a strange limitation in Backdrop and one that means I have to repeat a bunch of theming to get a simple nested menu. Oy.

![screen shot 2016-08-08 at 5 29 01 pm](https://cloud.githubusercontent.com/assets/998832/17497012/d0f47fec-5d8d-11e6-99e1-303f56fe460d.png)

![screen shot 2016-08-08 at 5 28 44 pm](https://cloud.githubusercontent.com/assets/998832/17497013/d1188f72-5d8d-11e6-817c-686195edf614.png)

**Comment by Gormartsen** [comment]
I assume it inherit Drupal behaviour here.

That's why I remember this issue, because I had to redefine primary menu depth on some d7 project.

**Comment by thekenshow** [comment]
No, just tested on pretty stock Drupal 7 and it uses the Show as Expanded setting of the parent menu item to determine whether or not to display nested menu items. Backdrop apparently ignores this.

**Comment by Gormartsen** [comment]
Do you have enough knowledge to find where exactly backdrop core ignore it and send PR?

Maybe we are missing something and it should work.

Regards,
Gor Martsen
@gormartsen
