### ISSUE TITLE
Sub theme not showing the changes made in the settings page

### ISSUE THREAD

**Issue by simone960** [backdrop-contrib/bootstrap_lite#15]
I have created a sub theme, enabled and set as default. I tried to make some changes e.g. change container type to "fluid" and selected a different Bootswatch theme. When I save, the settings page remain unchanged. However, if I go to the front end, the theme does show the changes I made. Any idea?

**Comment by stpaultim** [comment]
This request is a little light on details and over 3 years old. I will close this ticket for now, please reopen if you are experiencing a similar problem and/or have more details to share.
