### ISSUE TITLE
bootstrap 4 ?   Original issue: https://www.drupal.org/project/bootstrap/issues/2987988

### ISSUE THREAD

**Issue by joejoseph00** [backdrop-contrib/bootstrap_lite#17]
Any plans for a branch with bootstrap 4?

**Comment by stpaultim** [comment]
As far as I can tell, this theme has no active maintainer. Anyone interested?

**Comment by bugfolder** [comment]
Just making a note here for reference: people using this theme might well want to use the [Views Bootstrap](https://backdropcms.org/project/views_bootstrap) contrib module, which is built on Bootstrap 3. I've run into incompatiblities between Basis theme (which uses BS4 grid) and Views Bootstrap (using BS3.3.6 from the CDN), so any movement toward a BS4 version might include a warning to help people avoid hard-to-diagnose issues resulting from mixed BS versions.

**Comment by stpaultim** [comment]
I was just discussing this issue with a couple of users of Bootstrap Lite and our thought was that this theme should probably just remain focused on Bootstrap 3 and that if there is interest in a Bootstrap 4 version of this theme that we do one of the following:

1) We either start from scratch and build a new theme
2) Try to port a Bootstrap 4 based theme from Drupal
or
3) Fork this theme into a new theme and make it Bootstrap 4 compatible. Maybe call it `Bootrap 4 Lite`

We think that one large constituency for this theme is folks with Bootstrap 3 based sites in Drupal that are trying to port their themes to BackdropCMS. If a user is starting from scratch, why not start with a Bootstrap 4 dedicated theme. We don't really see the use case for someone installing this module and then later wanting to switch between Bootstrap 3 or 4. 

I'm told that Bootstrap 4 is quite significantly different from Bootstrap 3.

**Comment by bugfolder** [comment]
Yup, I agree with that assessment.

**Comment by stpaultim** [comment]
@bugfolder - My recommendation is that we leave this open for another 2 weeks, just in case anyone else has a concern or idea that we haven't considered yet. 

If we don't hear any objections - we go ahead and update the README to reflect this decision and then close this issue.

**Comment by stpaultim** [comment]
There is a Bootstrap Lite 5 - https://backdropcms.org/project/bootstrap5_lite
