### ISSUE TITLE
Support Bootswatch 4.0 themes

### ISSUE THREAD

**Issue by stpaultim** [backdrop-contrib/bootstrap_lite#24]
It appears that work was started on support for 4.0 Bootswatch themes. I rolled that back and opened a new feature branch to begin work on this support.

**Comment by stpaultim** [comment]
I assume that Bootswatch 4 themes would require Bootstrap 4. So if we leave this as a Bootstrap 3 only theme, there is no need or opportunity to provide support for Bootswatch 4.

**Comment by stpaultim** [comment]
I'm going to close this issue. I believe that we have decided on keeping this Bootstrap 3 only, correct @bugfolder?

**Comment by bugfolder** [comment]
Agreed.
