### ISSUE TITLE
Move the Bootswatch tab on the theme settings to top

### ISSUE THREAD

**Issue by stpaultim** [backdrop-contrib/bootstrap_lite#29]
We were discussing the fact that the Bootswatch options in Bootstrap Lite are pretty hidden and difficult to find, especially if you don't know what you are looking for. A user suggested that we move this tab on the settings page to the top to make it much easier for new users to the theme to notice these options. In some ways, for anyone using Bootstrap Lite without a sub-theme, this is the most important setting.

**Comment by bugfolder** [comment]
Related to that: I think there was a comment that the default Navbar position of "Static Top" looked better and so would be a better default value for the theme. Both of these changes would fall in the category of "cosmetic changes that make the theme more approachable for a beginner seeking an out-of-the-box theme."

**Comment by stpaultim** [comment]
I supposed we could wrap these two changes in together. I had been thinking about opening another Issue, but I'm actually looking at writing a PR right now and could combine them.

**Comment by bugfolder** [comment]
That's what I was thinking; easy enough to do them together.

**Comment by stpaultim** [comment]
OK, I have a PR that changes the order of the settings. It defaults to the Bootswatch settings, but in screenshot I opened the Navbar tab to show the new default. 

Thoughts?

![boostrap-settings](https://user-images.githubusercontent.com/3144571/108920633-98288c00-75fa-11eb-9991-3297b63d35fc.png)
