### ISSUE TITLE
Consider providing a local copy, rather than the CDN

### ISSUE THREAD

**Issue by bugfolder** [backdrop-contrib/bootstrap_lite#31]
Considering that [Bootstrap 3 reached EOL in 2019](https://blog.getbootstrap.com/2019/07/24/lts-plan/), there is the possibility that the CDN version might go away someday. We might consider adding an option to use a local version of the library bundled with the module. Since it's EOL, there will never be an update to the library, so we can rely on the bundled version being the last supported version.

BS3 is [MIT license](https://getbootstrap.com/docs/4.0/about/license/).

**Comment by stpaultim** [comment]
This makes sense to me. I would guess that some Backdrop users would prefer this choice anyway. Certainly for bootstrap, but what about FontAwesome and Bootswatch, do we do the same with both of these?

**Comment by bugfolder** [comment]
Bootswatch 3 is pretty tied to Bootstrap 3 and its last version number on the CDN (3.4.1) matches the last version number of Boostrap 3 (also 3.4.1). So that suggests they should get treated the same: both get an option to use a local bundled version.

FontAwesome seems different, though. The CDN version is 4.7.0, with older versions available. I don't know of any reason not to use the latest CDN version (which is currently one of our selections).

If we were to bundle FA, we'd need to use the [download version](https://fontawesome.com/how-to-use/on-the-web/setup/hosting-font-awesome-yourself), which is pretty big: 15 MB. And they only seem to offer version 5.x for download. 

FA is still in active development, and it looks like [version 5 is substantially different from version 4](https://fontawesome.com/how-to-use/on-the-web/setup/upgrading-from-version-4), if we bundled, we'd need to get v4 and bundle it.

**Comment by bugfolder** [comment]
> I would guess that some Backdrop users would prefer this choice anyway. 

[Recent Zulip conversations](https://backdrop.zulipchat.com/#narrow/stream/218635-Backdrop/topic/Carousel/near/263074061) would seem to bear this out. I'll start on this.

**Comment by bugfolder** [comment]
PR submitted. There's now a local copy of the Bootstrap and FontAwesome CSS and JS files (latest version) in addition to the various CDN versions.I still left Bootswatch in the CDN (and made CDN mandatory if Bootswatch theme is chosen), rather than providing all the Bootswatch options locally.

**Comment by bugfolder** [comment]
Having thought about this for a few days, I'm now thinking it doesn't make sense to provide bundled versions for Bootstrap and FontAwesome but not Bootswatch. The total Bootswatch library is 2 MB, which is not too huge to download (and those who are space-constrained can delete unused versions).

**Comment by bugfolder** [comment]
I've added a bundled version of Bootswatch. (This actually simplifies the logic a bit where it comes to loading the relevant CSS and JS files.) I also fixed an issue with the CSS on the settings page, so that the Bootswatch picker now displays smaller thumbnails on large screens (as was originally intended).
