### ISSUE TITLE
Missing body classes

### ISSUE THREAD

**Issue by allsite** [backdrop-contrib/bootstrap_lite#41]
I'm having a little trouble theming a node/add page and haven't figured out how to create a page template override to try to add classes myself. In D7 project/bootstrap I could move the page.tpl.php file into my subtheme and get my hands on the output. Perhaps someone could help me to override the template and even better the maintainer improving the out of box classes.

Here's the current body classes:
page logged-in cyborg navbar-is-static-top has-flexbox form-single-submit-processed

What I hoped to see and what I had in D7 project/boostrap:
page page-node page-node-add page-node-add-registration
(it's a page, it's a node page, it's a node add page, it's a node add page specifically for registration content type)

It's also nice to have the url components added as a body class:
For instance a view "mysite.com/people/developers" would get both "people" and "people-developers" classes added to the body tag

Lastly, it's also useful to have user roles in addition to "logged-in" added as classes. logged-in administrator

**Comment by bugfolder** [comment]
Bootstrap Lite wasn't intended to be fully identical to D7 Bootstrap (that's the "Lite" part), but that seems like a reasonable thing to add to the module (and I've missed its presence in some of my own upgrading from a D7 BS-based theme).

Marking this as an enhancement, and seeking further feedback from my co-maintainers (and anyone else who wants to chime in).

Meanwhile, as a stop-gap, if you create a subtheme, then implement `MYTHEME_preprocess_page()`, you can add those values to the `$variables['classes']` array, and they should get added to the `<body>` tag (see `core/modules/system/page.tpl.php`).

**Comment by allsite** [comment]
@bugfolder Fantastic! Thanks for getting this ball rolling and also providing in immediate solution for my project.

**Comment by bugfolder** [comment]
The PR adds body classes based on the normal path and on the user's roles.

@allsite, would you try out the PR and see if this addresses the issues you're after? And/or if there's any other suggested body classes to add.

@irinaz, let us know your thoughts here; it would make sense to strive for commonality with [bootstrap5_lite](https://github.com/backdrop-contrib/bootstrap5_lite/issues/6).

**Comment by stpaultim** [comment]
I approve.

**Comment by irinaz** [comment]
Thanks a lot, looks good to me!

**Comment by stpaultim** [comment]
I'm reopening this issue long enough to ask if we should edit the README to mention these additional classes as a feature of the theme. Some users might find these classes very helpful and would appreciate knowing that Bootstrap Lite provides them.
