### ISSUE TITLE
Header region abnormal output

### ISSUE THREAD

**Issue by allsite** [backdrop-contrib/bootstrap_lite#42]
Related to: https://github.com/backdrop-contrib/bootstrap5_lite/issues/7

Bootstrap_lite and Bootstrap5_lite suffer an issue pertaining to the styling and markup of the `<header>` element. 

In short, if you add "Header block" to the Header theme region in Layouts, you get a nice bootswatch styled header as expected. 

Now add another block to the Header theme region, say "Page Title block" and you'd expect it to appear in the same `<header>` tag, but this is not the case. Oddly a second `<header>` tag is output.

Themes that behave as expected (a single header tag with consistent classes/styling)- Basis, Shasetsu, Cleanish and D7/Bootstrap. 

Looking at examples on https://getbootstrap.com/ I was unable to find one with multiple header tags.

It seems fairly obvious any blocks in the Header theme region, added in Layouts, should output within a single `<header>` page element.

**Comment by allsite** [comment]
Layout config:
![image](https://user-images.githubusercontent.com/6035778/127591861-b2737167-9315-4f64-8e59-8eaeaa9b24a6.png)

Abnormal output (Page Title block in a second and unstyled header tag):
![image](https://user-images.githubusercontent.com/6035778/127591883-d769da66-8039-4c6e-a776-c9838827bdae.png)

Expected output (mockup, a single header tag with expected styles):
![image](https://user-images.githubusercontent.com/6035778/127591908-3dd56a0c-a56c-425c-95dc-8fc8bd37df30.png)

Basis output (all Header region blocks in a single header tag, expected result):
![image](https://user-images.githubusercontent.com/6035778/127591950-041bc5d0-912e-4a4f-aec4-df59186189bf.png)

**Comment by docwilmot** [comment]
As discussed in https://github.com/backdrop-contrib/bootstrap5_lite/issues/7 this isnt abnormal per se. Pages are allowed to have multiple header and footer regions. In this theme the top `<header` is a nave region, the other `<hearder>`s if any would be normal content regions.

In either case we can discuss further in https://github.com/backdrop-contrib/bootstrap5_lite/issues/7 if neede
