### ISSUE TITLE
Bootstrap broken when using custom template and bundled version of Bootstrap

### ISSUE THREAD

**Issue by stpaultim** [backdrop-contrib/bootstrap_lite#49]
1. I took the latest dev version of Bootstrap and applied to a basic site. 
2. I then created a custom layout for posts using Moscone Flipped layout
3. When I visit the default post included with core, Bootstrap is not working.

I replaced dev branch with last stable release and it works fine. Something in this release broke this page.

**Comment by stpaultim** [comment]
@bugfolder - It is only a problem when using the bundled version of bootstrap. Still not sure why?

**Comment by bugfolder** [comment]
OK, I can reproduce this. Looking into it.

**Comment by bugfolder** [comment]
Fixed. (It was an missing initial `'/'` on the paths to the bundled versions, so they weren't getting loaded.)
