### ISSUE TITLE
Primary Menu in Header does not Work  

### ISSUE THREAD

**Issue by vtad** [backdrop-contrib/bootstrap_lite#5]
No nav ,navbar etc. classes defined for the menu in the header block:

```
<header class="l-header" aria-label="Site header" role="banner">
<div class="contextual-links-region block block-system-main-menu block-menu">
<div class="contextual-links-wrapper contextual-links-processed">
<div class="block-content">
<ul class="menu">
<li class="first leaf active">
etc.
```

**Comment by Gormartsen** [comment]
Is website on local machine or available via Internet?

I would like to see it. If not, can you save full html and attach it here?

**Comment by vtad** [comment]
Info: to keep it simple I am using the "standard" 1 column Layout.
The Link is http://opi.vtadtest.de/

**Comment by Gormartsen** [comment]
Please add "Header block" (Contains elements typical of a site header including the site logo, name, slogan, and optionally a navigational menu.) instead of "Primary navigation".

**Comment by vtad** [comment]
Ok with Header Block it works, thanks
