### ISSUE TITLE
Reorganize libraries, expand documentation of icons

### ISSUE THREAD

**Issue by bugfolder** [backdrop-contrib/bootstrap_lite#54]
In working on an issue for Bootstrap 5 Lite (adding bundled libraries), I ran into two points that affect both modules.

## Add documentation of icons to README

 BSL uses the Bootstrap 3 library but also provides the FontAwesome 4 library of icons. BS3 has its own set of icons, so when both BS3 and FA4 are enabled, there's multiple ways to get similar icons. This could be confusing to users, so I have added some discussion of this point to the README.

## Reorganize bundled libraries

In the original implementation of the bundled libraries, the Bootstrap, Bootswatch, and FontAwesome CSS and JS files were woven into the theme's `/css` and `/js` directories (which also contained theme-specific files, e.g., `overrides.css`). If we ever decide to upgrade the bundled libraries, though, the new files will have to be similarly woven in. I think it will be cleaner to put Bootstrap, Bootswatch, and Font Awesome files into their own directories that are basically the same as their respective unzipped downloads, so that, in principle, we could upgrade a bundled library by just downloading the new library and dropping it into the appropriate place.

Since these directories now include the full downloads, they are larger than before; for example, they contain the unminified versions of the files. This makes the overall theme larger. In principle, we could go in and delete all the unminified files to reduce the size, at the cost of meaning that similar surgery would be needed any time a library is upgraded. We may also want to in the future give the user the option to use the unminified files for debugging purposes. So at this point, I'm inclined to leave the full libraries as they are.

PR to follow. Feedback welcome.

**Comment by stpaultim** [comment]
@bugfolder - I don't have strong feelings about how the libraries are bundled. I've looked at your PR and certainly don't see anything that concerns me. You can clearly thought about this far more than me, so I trust your judgement on this issue. 

I did notice a small thing. You edited the line in the README about creating subthemes. You redirected the link to: https://docs.backdropcms.org/documentation/developing-themes

I have two different thoughts.

1) Should we point directly at: https://docs.backdropcms.org/documentation/creating-sub-themes or do you think it's better that a user go the parent page first and then find their way to the sub-theming page. 
2) Should we mention this module as a possible resource. https://github.com/backdrop-contrib/devel_subthemer
I've tested the devel-subthemer module and think it's really helpful, however I doubt most folks are going to find it. We could help them. 

ALSO - maybe we should put a link to this module on https://docs.backdropcms.org/documentation/creating-sub-themes

**Comment by bugfolder** [comment]
> Should we point directly at: https://docs.backdropcms.org/documentation/creating-sub-themes

Yes, good suggestion.

> Should we mention [Devel Subthemer] module as a possible resource?

Yes.

> ALSO - maybe we should put a link to this module on https://docs.backdropcms.org/documentation/creating-sub-themes.

Agreed, I've added it to https://docs.backdropcms.org/documentation/creating-sub-themes.

**Comment by bugfolder** [comment]
README file is updated with mention of sub-theming and Devel Subthemer module.

**Comment by stpaultim** [comment]
@bugfolder - I reviewed your changes to the README. They look good.
