### ISSUE TITLE
Packaging Error

### ISSUE THREAD

**Issue by vtad** [backdrop-contrib/bootstrap_lite#7]
Please correct the packaging error so that this Theme appears in
 https://backdropcms.org/themes

**Comment by Gormartsen** [comment]
Tnx! Will check it out. 
Can you be more specified what exactly need to be fixed ?

**Comment by vtad** [comment]
If you look at PACKAGING_ERROR_LOG.txt under releases (https://github.com/backdrop-contrib/bootstrap_lite/releases)  you see that type property ("type = theme") is missing in the info file. 
Also (not an error) you should set the version to 1.x-3.3.5.2, so its the same as the release version.

**Comment by Gormartsen** [comment]
Thank you @vtad . Fixed.
